### ISSUE TITLE
Feature request: 

### ISSUE THREAD

**Issue by janCstoffregen** [dhlab-basel/Kuirl#39]
**Is your feature request related to a problem? Please describe.**
You have to start Knora in addition to starting Kuirl

**Describe the solution you'd like**
a docker-compose.yml which pulls a latest Knora and a latest Kuirl docker image from dockerhub, this file should already have all environments set so that all parts of the stack work together without any necessary further actions.. This would enable the user to start Knora, a triplestore and Kuirl and possible Sipi and maybe a key-value store with only one comment.

**Describe alternatives you've considered**
I don't know of any alternative, but maybe Kuirl can be added to the docker-compose file in the Knora - Repo?

**Comment by kilchenmann** [comment]
Thank you @janCstoffregen for your input. I think, we will integrate Kuirl into the docker-compose file of Knora one day.

**Comment by subotic** [comment]
I began working on something, but it is not finished yet: https://github.com/dasch-swiss/knora-docker-app. It will use the new Dockerapp feature.

The idea is to be able to start only the services which are needed for ones work. For example, if someone wants to work on Knora-API, then he would start the whole stack minus the Knora-API. The same if someone wants to work on Kuirl, then he would need the whole stack minus Kuirl.

**Comment by janCstoffregen** [comment]
ok, then it's already on the way, I'm looking forward to it!

The Dockerfile for an angular app is very simple btw, just compile it with ng build and then copy the dist to a proxy - docker - image.
You don't have to build the angular app in the docker image, that causes lot's of extra stress because the yarn / npm packages have different problems on a Dockerfile with a different OS underneath, just build it locally on your macbook, generate the docker image and push it to dockerhub once in a while. 
That's my experience at least, please correct me when I'm wrong, I know it would be nicer in an automated way but it does not work for me without extra effort at the moment, so it does not save time in my case in the end.

I don't know the new Dockerapp feature and will check it out, thank you for the hint!

**Comment by subotic** [comment]
We build all our Angular apps automatically through docker. You can take a look at https://github.com/dhlab-basel/Kuirl/blob/master/Dockerfile

Every time we set a tag on this repository, Dockerhub starts building the image into this repository: https://cloud.docker.com/u/daschswiss/repository/docker/daschswiss/knora-app-web

**Comment by subotic** [comment]
This requires that you can provide the config to your application at runtime and not buildtime. We build the app once and then deploy it in different environments.

**Comment by janCstoffregen** [comment]
I tried the "build once deploy anywhere" way, André told me that you're successfully doing this, I'll have to have a look, when I tried it, I stored the different configurations in the asset folder, sometimes the environment variables were not loaded fast enough, I have to check out your solution!

I only checked out the dhlab docker hub, thank you for pointing this repo out, then it's already available as a docker image as well, that's quite nice.

I'll wait for the dockerapp then, thank you very much, please feel free to close this issue if it is at the wrong repo, I know now where to check the status of this.

**Comment by kilchenmann** [comment]
I think we can close this issue
