### ISSUE TITLE
Feature request: block the login of a "deleted" user

### ISSUE THREAD

**Issue by flavens** [dhlab-basel/Kuirl#42]
**Is your feature request related to a problem? Please describe.**
"Delete user" can still login to the web app.

**Describe the solution you'd like**
- Change the label "Delete user" to "Suspended" user.
- A suspended user cannot log in.

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by kilchenmann** [comment]
This is already done...
