### ISSUE TITLE
Update to Angular 8

### ISSUE THREAD

**Issue by kilchenmann** [dhlab-basel/Kuirl#48]

**Comment by subotic** [comment]
###### do-not-edit-start-codetree-epic-issues

#### Issues in this epic:

Title | Milestone | Assignees | Stage | State
----- | --------- | --------- | ----- | -----
![](https://cdnjs.cloudflare.com/ajax/libs/octicons/4.4.0/svg/issue-opened.svg) [Update to Angular 8 #274](https://github.com/dhlab-basel/Knora-ui/issues/274)  [![](https://codetree.com/small_codetree_logo.png)](https://codetree.com/projects/J18Y/issues/9885466) | N/A | flavens, kilchenmann | Untriaged | Open


###### do-not-edit-end-codetree-epic-issues

**Comment by kilchenmann** [comment]
@subotic What do you mean with "do-not-edit-start-codetree-epic-issues"? We just started to use codetree and we have to understand how and where to add issues. Is there a guideline how to use it?

**Comment by kilchenmann** [comment]
This issue shouldn't be an epic one. We will close it when it's done in September.
