### ISSUE TITLE
Question: can we already sort the advanced search results?

### ISSUE THREAD

**Issue by mrivoal** [dhlab-basel/Kuirl#58]
**Is your feature request related to a problem? Please describe.**
I understood that in KUIRL the search results could already be sorted using selected properties. But I can't see how (I was using your test server and KUIRL v.1.3.0)

**Describe the solution you'd like**
In the screenshot, I would have expected to click either on `Date de creation` or `Emplacement` (just like I would on a column header in a speadsheet) to be able to sort the search results alternatively by creation date or location. But it is not yet possible to do so, right?

![Capture d’écran 2019-08-26 à 15 52 01](https://user-images.githubusercontent.com/17294309/63695829-c4065e00-c819-11e9-8c1f-666a7b94d9db.png)

**Describe alternatives you've considered**
-
**Additional context**
-

**Comment by flavens** [comment]
@mrivoal I am able to sort by location here: 
<img width="982" alt="Screenshot 2019-08-26 at 16 31 08" src="https://user-images.githubusercontent.com/29532462/63698346-f5355d00-c81e-11e9-9e04-c20672af95f4.png">
I get Basel first, then Berlin, etc. 
I check the sort criterion checkbox, and set the operator to Exist

**Comment by kilchenmann** [comment]
The solution (which is not the best at the moment) is to check the little box on the right handside. This checkbox will priories the search criteria on this field. In your case it sorts by "Standort".

**Comment by mrivoal** [comment]
Thanks! I missed the checkbox. 

So, we can already sort search results by ascending order.
