### ISSUE TITLE
style: Change label of Zurück button

### ISSUE THREAD

**Issue by flavens** [dhlab-basel/Kuirl#72]
**Is your feature request related to a problem? Please describe.**
It does not make sense to display only this button label in German.
<img width="171" alt="Screen Shot 2019-09-05 at 15 23 49" src="https://user-images.githubusercontent.com/29532462/64345808-46003f00-cff1-11e9-8a2e-86e7fe46db3d.png">

**Describe the solution you'd like**
For now, use only English: `Back`.

**Describe alternatives you've considered**
N.A.

**Additional context**
N.A.

**Comment by kilchenmann** [comment]
We have to clean up the labels anyway. In some cases we are using the multi language (i18n) support to translate and in some cases we have words 'hardcoded' in the template. And in some cases it comes from outside.
Yes I agree to set everything to English.
