### ISSUE TITLE
feat: Add link from doc to web app and vice-versa 

### ISSUE THREAD

**Issue by flavens** [dhlab-basel/Kuirl#81]
**Is your feature request related to a problem? Please describe.**
There is currently no link from the Kuirl User Guide to the web app, and from the web app to Kuirl User Guide.

**Describe the solution you'd like**
Add a visible link to the doc and the web app to link each other.

**Describe alternatives you've considered**
N.A.

**Additional context**
These links will be needed by the user testers during the user testing phase.

**Comment by kilchenmann** [comment]
@flavens: I can do that.

**Comment by kilchenmann** [comment]
I just added links to the web app on the new documentation page.
