### ISSUE TITLE
feat: Add DaSCH contact information somewhere in the logged-in part

### ISSUE THREAD

**Issue by flavens** [dhlab-basel/Kuirl#82]
**Is your feature request related to a problem? Please describe.**
There is a section with DaSCH contact information in the footer of the logged-out homepage but there is nothing in the logged-in part. 

**Describe the solution you'd like**
Contact information should be added on the dashboard or in the user menu > tab e.g."Need help" or "Contact DaSCH" or something equivalent. 

**Describe alternatives you've considered**
Contact form.

**Additional context**
N.A.

**Comment by kilchenmann** [comment]
Good point
